### ISSUE TITLE
Beatless Intermission 

### ISSUE THREAD

**Issue by xChickens** [erengy/anime-relations#27]
So I didn't want to put this into a pull request since I couldn't get it to work when I attempted it (multiple different ways), but there's a series called Beatless that has some really dumb things in which there are 4 recap episodes spread throughout the 24 episodes it has. These episodes are 6, 11, 17, and 20, of which they each displace the episode count by 1, so in actuality the series should has aired 20 episodes (which both MAL and Kitsu list correctly). So episodes 7-10 should equal 6-9, 12-16 -> 10-14, 18-19 -> 15-16, and 21-24 -> 17-20 (this is also the same for Anilist). Then 6, 11, 17, and 20 should represent episodes 1-4 of Beatless Intermission, which is a listing on MAL and Kitsu.

**Comment by wopian** [comment]
Note that Amazon Prime was the only one that merged the Intermissions. Fansubs and Raw sources of Beatless only go up to 20

**Comment by erengy** [comment]
MAL and Kitsu have separate entries for *Intermission* and *Final Stage*, whereas AniList has *Final Stage* appended to the series. In other words, all services are consistent with the first 20 episodes, leaving the recap episodes of *Intermission* out.

The situation with the official and fansub releases is complicated, though. Creating rules to cover some of them would cause incorrect redirections for the others. I don't think we should do that in this case.

**Comment by xChickens** [comment]
@wopian HorribleSubs goes up to 24 which is primarily the downloaded version on nyaa

**Comment by wopian** [comment]
>HorribleSubs goes up to 24 which is primarily the downloaded version on nyaa.

Which is a rip of the Amazon Prime stream. HS isn't a fansub group.

**Comment by xChickens** [comment]
> Which is a webrip of the Amazon Prime stream. HS isn't a fansub group.

Ignoring that they explicitly state otherwise on their [website](https://horriblesubs.info/about-us/) (which of course could be deceit), your note implies that there is a significant group of viewers of the series that are not benefiting from the rule change that I suggest in the original post, when in fact it's more than just the opposite. 

Just judging by numbers, those who downloaded from HorribleSubs number almost 80x more than the only other FanSub group (Asuka Subs) on the last episode of the series (11811 vs 148 on the sum of the torrents). 

All in all, I would still say the change would be beneficial to the majority of English watchers of the series. But like I said, if anime-relations doesn't have a way to already implement such rules, then it would be fine to ignore them.

**Comment by erengy** [comment]
The rules would be something like this:

```
# Beatless -> ~ Intermission
- 36516|13939|?:6 -> 37277|41051|?:1
- 36516|13939|100245:7-10 -> 36516|13939|100245:6-9
- 36516|13939|?:11 -> 37277|41051|?:2
- 36516|13939|100245:12-16 -> 36516|13939|100245:10-14
- 36516|13939|?:17 -> 37277|41051|?:3
- 36516|13939|100245:18-19 -> 36516|13939|100245:15-16
- 36516|13939|?:20 -> 37277|41051|?:4
- 36516|13939|100245:21-24 -> 36516|13939|100245:17-20
```

The thing is, Taiga only redirects invalid episode numbers, which is why only the last rule above would work. If it's already within the allowed range (1-20 in this case), Taiga doesn't check redirections at all. This is intentional, since redirecting valid episode numbers is generally not a good idea.

I decided not to take any action here, but I'll reconsider if we end up seeing more cases like this.

**Comment by tophf** [comment]
> I'll reconsider if we end up seeing more cases like this.

`Chuukan Kanriroku Tonegawa` (24 eps) and its spin-off `1-nichi Gaishutsuroku Hanchou` (1 ep aired, more might air sometime in the future) which was released as ep 14 of the main show by HorribleSubs?

**Comment by tophf** [comment]
Yeah, I know, but it's also 1-nichi Gaishutsuroku Hanchou so I thought it's the same case. Now I think it's not, and there was probably no need to make a separate db entry for Hanchou.
