### ISSUE TITLE
Shingeki no Kyojin S3 Part 2 not working

### ISSUE THREAD

**Issue by thekramnella** [erengy/anime-relations#46]
Taiga isn't recognizing HorribleSubs' releases for Shingeki no Kyojin S3. They are grayed out in the torrent feed. Not sure if it matters, but I'm using AniList.

**Comment by thekramnella** [comment]
I changed a line and it recognizes "Shingeki no Kyojin S3 - 53" as "Shingeki no Kyojin 3 Part 2 - 4", but it still won't select the torrent for download. The episode is marked as currently airing and matches my selection filter, so not sure what is going on now.

**Comment by erengy** [comment]
The current rules for *Shingeki no Kyojin S3 Part 2* work correctly for AniList without requiring any modifications. Tested again now to be sure. You can download [anime-relations.txt](https://raw.githubusercontent.com/erengy/anime-relations/master/anime-relations.txt) manually, in case you've got an older one in your data directory.

The other issue you mentioned is not related to anime-relations, but you can try clearing any alternative titles you set for the series.
