### ISSUE TITLE
Question about commit involving Re:Zero season 2 part 2

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [erengy/anime-relations#73]
I'm running version 1.3.1 of Taiga and anime-relations.txt lists the last update as 2021-01-12.
Forgot to mention I am using AniList for my updates in case that matters.

I'm wondering about the reason for the Re:Zero rule in e6f6b65d04e9cb9bfe7150f539c11a497318a629.

It seems like the episode count for 14 -> 1 would be for some sub group, but it is not working for [SubsPlease] who have this starting at 39.

I tried adding another rule, but it seems like it wont recognize it over the existing one from the latest file.

Filename:
`[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 39 (720p) [F1D69DBE]`

With the rule from this file it considers it as episode 26.
```
# Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season -> ~ Part 2
- 39587|42198|108632:14-? -> 42203|43247|119661:1-?!
```

The only way I was able to fix it for me was changing the 14 to 39.
I don't want to submit a pull request for this if the change would break something for others.
```
# Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season -> ~ Part 2
- 39587|42198|108632:39-? -> 42203|43247|119661:1-?!
```

Is there a conflict with recognition on my end?
My folder is called 
`Re Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2`
but each episode just has 
`Re Zero kara Hajimeru Isekai Seikatsu`

**Comment by erengy** [comment]
There are two rules for the series:

```
# Re:Zero kara Hajimeru Isekai Seikatsu -> ~ 2nd Season Part 2
- 31240|11209|21355:39-? -> 42203|43247|119661:1-?!
```

```
# Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season -> ~ Part 2
- 39587|42198|108632:14-? -> 42203|43247|119661:1-?!
```

First one was added in 9e1c957437ffad2505f05501d9f5f0a76ff37703 and it works for releases starting at 39 (e.g. SubsPlease). Second one was added afterwards in e6f6b65d04e9cb9bfe7150f539c11a497318a629 to cover other releases starting at 14 (e.g. Judas). I also just committed bd7586a8755d1e703bf9769cd11de8e6c090de54, which might help with your situation.

These together work correctly (with AniList on a fresh installation) for almost all releases, including SubsPlease. I imagine you have an invalid alternative title set for the series, which causes Taiga to select the incorrect redirection. If that's the case, removing the alternative title would resolve your issue.

**Comment by ClawhammerLobotomy** [comment]
The latest change does seem to address the issue.

I'm also thinking the alternate title was an issue on my end previously.
Looks like things are working now, so thanks for taking a look.
